### ISSUE TITLE
Where can I find the DS-GCN configuration file?

### ISSUE THREAD

**Issue by leo917** [davelailai/DS-GCN#1]
The configuration file for DS-GCN is not found in the configuration folder provided
Where can I find the DS-GCN configuration file?
![4](https://github.com/davelailai/DS-GCN/assets/30929167/feee26b6-f443-4b11-86e5-8162dedccebc)

**Comment by davelailai** [comment]
you can run our method with the folder of dsdtgcn

**Comment by leo917** [comment]
Many thanks
